x-base_service: &base_service
    expose:
      - "7860"  # Backend will be exposed to NGINX proxy, but not the host.
    networks:
      - private
    volumes:
      - &data ./data:/data
      - &output ./output:/output
    stop_signal: SIGKILL
    tty: true
    depends_on:
      - proxy
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]

name: webui-docker

services:
  proxy:
    image: nginx:1.27.4-bookworm-perl
    ports:
      - "${WEBUI_PORT:-8080}:8080"
    volumes:
      - ./config/nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      - public
      - private

  download:
    build: ./services/download/
    profiles: ["download"]
    networks:
      - public
    volumes:
      - *data

  auto: &automatic
    <<: *base_service
    container_name: auto
#    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:78
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api

  auto-cpu:
    <<: *automatic
    profiles: ["auto-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api

  comfy: &comfy
    <<: *base_service
    profiles: ["comfy"]
    build: ./services/comfy/
    image: sd-comfy:7
    environment:
      - CLI_ARGS=

  comfy-cpu:
    <<: *comfy
    profiles: ["comfy-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--cpu

networks:
  public:
    driver: bridge
    # Setting this to "true" will constrain the SD UI applications to an
    #   internal network, restricting user access to the NGINX reverse proxy and
    #   ensuring that any AI does not have direct access to the open Internet.
    #
    #  This is set to "false" by default, as there are many functions this will
    #  undoubtedly break, but keeping Skynet inside a box will ease the minds of
    #  more paranoid users.
    internal: false
  private:
    driver: bridge
    internal: false
